### ISSUE TITLE
Add a search for event names and places

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-events#144]
as a user 
 i would like to search for an event happening in a particular location or a particular event.
so that i would find what i want easly

# Acceptance criteria

- [x] let webpack bundle hbs files so they could be used in the frontend - #149 
- [x] connect the tempalte in the frontend with the ajax call that happens when we start the app and make it functional with the current exsisting filters  - #151  
- [x] add a search input which goes through and filters the data we got from the first ajax request ( with the event and places ) - #157

**Comment by Karyum** [comment]
@des-des do you think this still needs to be debounced ?? cause it's just recompiling the HBS in the frontend and not making an API call every-time someone inputs a letter

**Comment by des-des** [comment]
@Karyum No, only request needs to be debounced, not re-renders.

ps (hopefully we are not recompiling the hb templates, only re-calling the render func)

**Comment by Karyum** [comment]
```js
  const template = homeView({
    events: filteredEvents,
    lang: state.lang,
    calendarButton: true,
    filterButtons: true,
    english: state.lang === 'en',
    arabic: state.lang === 'ar',
    currentDate: state.date_from || new Date().toISOString().split('T')[0]
  });
  document.getElementById('root').innerHTML = template;
  initCalendarEventListener(eventsState);
```
So we are recompiling cause it's different data every time, i can't see how you would do it without recompiling and reinitialising the event listeners ??

**Comment by des-des** [comment]
No it is all good. We are executing a compiled template here, not compiling one.

Note the difference: http://handlebarsjs.com/
