### ISSUE TITLE
Enhance the category filtering functionality and design 

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-events#145]
Currently filtering categories with the dropdown list has loads of bugs and is just a bad UI/UX for the user, in the new design #141 they are gonna change to checkboxes rather than a dropdown list.

# Acceptance criteria

- [x] redesign categories filter to be checkboxes  - # 
- [x] implement the functionality - #153 

# stretch goals

- [x] render only the categories that exist in the app ( so if a category has no event, then theres no point of giving an option to render by that category ) #153
