### ISSUE TITLE
Event image upload

### ISSUE THREAD

**Issue by Karyum** [foundersandcoders/nazareth-events#99]
As an events planner
I would like to be able to upload a photo of my event
Because I am not technical and don't know how to make my own photo url

### Acceptance criteria
- [ ] Set up an S3 bucket #105 
- [ ] Add photo upload field to the event form
- [ ] Integrate S3 API into the app
- [ ] Check it works on both mobile and desktop

**Comment by finnhodgkin** [comment]
Heroku's documentation have [a good guide](https://devcenter.heroku.com/articles/s3-upload-node) for setting up s3.

**Comment by Karyum** [comment]
we are waiting on @sofer's answer on the deployment costs after he meets with Waleed Afifi, until then this issue would have to wait.

**Comment by Karyum** [comment]
closing this issue since the add event functionality was removed
